version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-vite-app-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node-modules-react-vite:/app/node_modules
    depends_on:
      - backend
    env_file:
      - ./backend/.env
    environment:
      - VITE_API_URL=http://localhost:5000/api
    command: npm run dev

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: express-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
    volumes:
      - ./backend:/app
      - node-modules-backend:/app/node_modules
      
    command: npm run dev
    working_dir: /app

volumes:
  node-modules-react-vite:
  node-modules-backend:
